version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    networks:
      - some_network


      
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - some_network

networks:
  some_network:  

volumes:
  data:
  logs:
 